CREATE TABLE PM_PAGEMONITORED (
    id INT NOT NULL AUTO_INCREMENT,
    userId INT NOT NULL,
    url VARCHAR(256) NOT NULL,
    lastChangeDetected DATE NOT NULL,
    lastCheckDone DATE NOT NULL,
    checkFrequencyMin INT NOT NULL,
PRIMARY KEY (id)
);
ALTER TABLE PM_PAGEMONITORED ADD CONSTRAINT PM_PAGEMONITORED$FK_UserId FOREIGN KEY(userId) REFERENCES PM_USER(id);

CREATE TABLE PM_CHANGEDETECTED (
    id INT NOT NULL AUTO_INCREMENT,
    pageMonitoredId INT NOT NULL,
    dateChangeDetected DATE NOT NULL,
    html LONGTEXT NOT NULL,
PRIMARY KEY (id)
);
ALTER TABLE PM_CHANGEDETECTED ADD CONSTRAINT PM_CHANGEDETECTED$FK_PageMonId FOREIGN KEY(pageMonitoredId) REFERENCES PM_PAGEMONITORED(id);
